# Generated by Django 4.2.6 on 2023-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField()),
                ('preço', models.CharField(max_length=20)),
                ('endereço', models.CharField(max_length=200)),
                ('metros_quadrados', models.CharField(max_length=10)),
                ('quarto', models.CharField(max_length=2)),
                ('banheiro', models.CharField(max_length=2)),
                ('estacionamento', models.CharField(max_length=2)),
            ],
        ),
    ]
