# Generated by Django 4.2.6 on 2023-10-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imoveis',
            new_name='Imovel',
        ),
    ]
