# Generated by Django 4.2.6 on 2023-11-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_rename_imoveis_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
