# Generated by Django 4.2.6 on 2023-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens'),
        ),
    ]
